# Generated by Django 3.2.1 on 2021-05-05 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=40, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('open', models.BigIntegerField(blank=True, null=True)),
                ('high', models.BigIntegerField(blank=True, null=True)),
                ('low', models.BigIntegerField(blank=True, null=True)),
                ('close', models.BigIntegerField(blank=True, null=True)),
                ('diff', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyState',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('company_nm', models.CharField(max_length=20)),
                ('set_base_date', models.CharField(max_length=20)),
                ('update', models.DateField(default=datetime.datetime(2021, 5, 5, 7, 28, 48, 382846, tzinfo=utc))),
                ('sec', models.CharField(max_length=10)),
                ('sec_nm', models.CharField(max_length=30)),
                ('mk', models.CharField(max_length=20)),
                ('rp_type', models.CharField(max_length=30)),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('debt_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('quick_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('bis', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('fin_badness', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('sales_growth_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('asset_growth_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('net_profit_growth_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('roa', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('gross_margin', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('pbr', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('per', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('asset_turnover', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'company_state',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='companystate',
            constraint=models.UniqueConstraint(fields=('code', 'set_base_date'), name='company code'),
        ),
    ]
