# Generated by Django 3.1.5 on 2021-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=40, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('open', models.BigIntegerField(blank=True, null=True)),
                ('high', models.BigIntegerField(blank=True, null=True)),
                ('low', models.BigIntegerField(blank=True, null=True)),
                ('close', models.BigIntegerField(blank=True, null=True)),
                ('diff', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompState',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('account_nm', models.CharField(max_length=40)),
                ('equity', models.BigIntegerField(blank=True, null=True)),
                ('last_equity', models.BigIntegerField(blank=True, null=True)),
                ('liabilities', models.BigIntegerField(blank=True, null=True)),
                ('currentLiabilities', models.BigIntegerField(blank=True, null=True)),
                ('last_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('currentAssets', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('last_revenue', models.BigIntegerField(blank=True, null=True)),
                ('inventories', models.BigIntegerField(blank=True, null=True)),
                ('netIncome', models.BigIntegerField(blank=True, null=True)),
                ('last_netIncome', models.BigIntegerField(blank=True, null=True)),
                ('operatingExpenses', models.BigIntegerField(blank=True, null=True)),
                ('financialIncome', models.BigIntegerField(blank=True, null=True)),
                ('financeCosts', models.BigIntegerField(blank=True, null=True)),
                ('nonOperExpenses', models.BigIntegerField(blank=True, null=True)),
                ('corporateTax', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yearly_comp_state',
                'managed': True,
                'unique_together': {('code', 'date')},
            },
        ),
    ]
