# Generated by Django 3.2.1 on 2021-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=40, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('open', models.BigIntegerField(blank=True, null=True)),
                ('high', models.BigIntegerField(blank=True, null=True)),
                ('low', models.BigIntegerField(blank=True, null=True)),
                ('close', models.BigIntegerField(blank=True, null=True)),
                ('diff', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyState',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('year', models.SmallIntegerField()),
                ('sec', models.CharField(max_length=10)),
                ('sec_nm', models.CharField(max_length=20)),
                ('company_nm', models.CharField(max_length=20)),
                ('rp_type', models.CharField(max_length=30)),
                ('mk', models.CharField(max_length=40)),
                ('last_update', models.DateTimeField()),
                ('current_asset', models.BigIntegerField(blank=True, null=True)),
                ('total_sales', models.BigIntegerField(blank=True, null=True)),
                ('net_profit', models.BigIntegerField(blank=True, null=True)),
                ('operating_profit', models.BigIntegerField(blank=True, null=True)),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('debt_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('quick_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('bis', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('sales_growth_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('asset_growth_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('net_profit_growth_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('eps', models.IntegerField(blank=True, null=True)),
                ('roa', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('gross_margin', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('pbr', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('per', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('bps', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('asset_turnover', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'company_state',
                'managed': True,
            },
        ),
    ]
