# Generated by Django 3.2.1 on 2021-05-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystate',
            name='sec_nm',
            field=models.CharField(max_length=50),
        ),
    ]
