# Generated by Django 3.2.1 on 2021-06-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCap',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sec', models.CharField(max_length=10)),
                ('sec_nm', models.CharField(max_length=50)),
                ('company_nm', models.CharField(max_length=20)),
                ('mk', models.CharField(max_length=40)),
                ('mk_cap', models.BigIntegerField(blank=True, null=True)),
                ('number_of_stocks', models.BigIntegerField(blank=True, null=True)),
                ('last_update', models.DateField()),
            ],
            options={
                'db_table': 'market_cap',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='companystate',
            name='fair_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
