# Generated by Django 3.2.1 on 2021-06-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0002_auto_20210606_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystate',
            name='fair_price',
        ),
    ]
